### PR TITLE
Work in progress

### PR DESCRIPTION
**Pull request by crodeheaver**
Don't judge my code. It's a bit thrown together. The database schema could use a bit of work. I had a nice clean code base, but my user kept changing her mind on what she wanted, so things got a little strung together. The sentence, "I know I said {{insert not needed requirement}}, but I'd really like that now", was said more than a few times.

I plan on changing the database schema, cleaning up some of the templates (there is a bit of code duplication in a couple), adding some ajax calls, adding sessions, and adding authentication. I haven't done any of the last three things before, so it's gonna be a learning experience. But I figure for the purposes of this class, I've got the basics covered. If I find the time, I'm going to add a few of those things before this is due.

@barberboy Thoughts and suggestions are always welcome.

### CODE REVIEW

**Comment by crodeheaver** [comment]
team.members.push.apply(team.members, req.body.players) is fantastic! Thank you!

**Comment by crodeheaver** [comment]
Though part of me was hoping you were going to say that the chained asynchronous queries were a terrible way of doing things and that you had a better way of doing them. I guess I can't have everything.

**Comment by crodeheaver** [comment]
@barberboy Upon further investigation, I definitely think you're right about the aggregation.

https://docs.mongodb.org/v3.0/reference/operator/aggregation/addToSet/#grp._S_addToSet

I think that is essentially what I'm looking for and will make life a million times easier. Instead of querying the team collection 3 times, I can just add each of them to a separate set based of their section.

**Comment by barberboy** [comment]
I ran into a few bugs and issues when I ran though it, but overall it's an appropriately ambitious project for you, and is well done.

Great work, Colby.
:100:

**Pull request closed without merging**
